name: OpenWrt mirror to gitee

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
  schedule:
   - cron: 0 */4 * * *
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Download dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        pip3 install requests

    - name: Sync repo
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 55
        max_attempts: 3
        command: |
          export USERNAME=${{ secrets.USERNAME }}
          export PASSWORD=${{ secrets.PASSWORD }}
          export GITEE_PAT=${{ secrets.GITEE_PAT }}

          python3 ./sync_repo.py

