name: OpenWrt mirror to gitee

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
  schedule:
   - cron: 0 */4 * * *
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Sync repo
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        export USERNAME=${{ secrets.USERNAME }}
        export PASSWORD=${{ secrets.PASSWORD }}

        python3 ./sync_repo.py
    
