name: OpenWrt mirror to gitee

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
  schedule:
   - cron: 0 8 * * *
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Clone repo
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        git clone --bare https://github.com/NobyDa/Script.git
        git clone --bare https://github.com/openwrt/openwrt.git

    - name: Push repo
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        cd openwrt.git && git push --mirror https://${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}@gitee.com/duchenpaul/openwrt.git && cd ..
        cd Script.git && git push --mirror https://${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}@gitee.com/duchenpaul/QuanX_Script.git && cd ..

    
